version: '3.4'

services:
  weatherdemo-webapi:
    image: ${DOCKER_REGISTRY-}weatherdemowebapi
    build:
      context: .
      dockerfile: src/WeatherDemo.WebApi/Dockerfile
    expose:
      - "80"
    ports:
      - "8686:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - OpenWeatherMap:ApiKey=${APIKEY}

  weatherdemo-webui-blazor:
    image: ${DOCKER_REGISTRY-}weatherdemowebuiblazor
    build:
      context: .
      dockerfile: src/WeatherDemo.WebUI.Blazor/Dockerfile
    expose:
      - "80"
    ports:
      - "8585:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - weatherdemo-webapi
    
